# Generated by Django 2.0.1 on 2018-01-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='debet',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='account',
            name='percent_rate',
            field=models.FloatField(blank=True, default=0.13),
            preserve_default=False,
        ),
    ]
