# Generated by Django 2.0.1 on 2018-01-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20180124_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='percent_pay_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='percent_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
